# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IjqXlsEsVQhyfoY9BTy46WF70SXgICRz
"""

import keras
import tensorflow as tf
from keras.datasets import cifar10
from tensorflow import keras
from tensorflow.keras.optimizers import RMSprop
import pandas as pd
import numpy as np

(x_train,y_train),(x_test,y_test) =cifar10.load_data()

import matplotlib.pyplot as plt
plt.imshow(x_train[1])

num_classes=10
print('before',y_test[4])

y_train=keras.utils.to_categorical(y_train,num_classes)
y_test=keras.utils.to_categorical(y_test,num_classes)
print('after',y_test[4])
x_train=x_train/255.0
x_test=x_test/255.0

model=tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                                 tf.keras.layers.Dense(1024,activation=tf.nn.relu),
                                 tf.keras.layers.Dense(128,activation=tf.nn.relu),
                                 tf.keras.layers.Dense(10,activation=tf.nn.softmax)])

model.compile(loss='binary_crossentropy',optimizer=RMSprop(lr=0.001),metrics=['acc'])
model.fit(x_train,y_train,epochs=10)

model.evaluate(x_test,y_test)

model.summary()

import numpy as np
from google.colab import files
from keras.preprocessing import image
upload=files.upload()

for fn in upload.keys():
  path='/content/'+fn
  img=image.load_img(path,target_size=(32,32))
  x=image.img_to_array(img)
  x=np.expand_dims(x,axis=0)
  images=np.vstack([x])
  classes=model.predict(images,batch_size=10)

print(classes)
classes2=np.argmax(classes,axis=1)
if(classes2[0]==0):
  print("aeroplane")
if(classes2[0]==1):
  print("automobile")
if(classes2[0]==2):
  print("bird")
if(classes2[0]==3):
  print("cat")
if(classes2[0]==4):
  print("deer")
if(classes2[0]==5):
  print("dog")
if(classes2[0]==6):
  print("frog")
if(classes2[0]==9):
  print("truck")  
if(classes2[0]==8):
  print("ship")

